apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wedding-server
  template:
    metadata:
      labels:
        app: wedding-server
    spec:
      containers:
      - name: wedding-server
        image: wedding-server:1.0
        envFrom:
        - configMapRef:
            name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: wedding-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: wedding-server
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30303
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: wedding-server
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: wedding-server
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 32345
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wedding-server
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: wedding-server
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: wedding-server
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
